import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface PDFData {
  clientName: string;
  totalValue: number;
  totalReturn: number;
  holdingsCount: number;
  sharpeRatio: number;
  beta: number;
  maxDrawdown: number;
  diversificationScore: number;
  holdings: Array<{
    symbol: string;
    shares: number;
    value: number;
    allocation: number;
    return: number;
  }>;
  recommendations: Array<{
    action: string;
    reason: string;
    impact: string;
  }>;
}

export function generatePortfolioReport(data: PDFData): void {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.setTextColor(40);
  doc.text('SamrAI Portfolio Report', 105, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 105, 28, { align: 'center' });

  let yPos = 40;

  // 1. CLIENT SUMMARY
  doc.setFontSize(14);
  doc.setTextColor(40);
  doc.text('Client Summary', 14, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text(`Client: ${data.clientName}`, 14, yPos);
  yPos += 6;
  doc.text(`Total Portfolio Value: $${data.totalValue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 14, yPos);
  yPos += 6;
  doc.text(`Number of Holdings: ${data.holdingsCount}`, 14, yPos);
  yPos += 6;
  doc.text(`Total Return: ${data.totalReturn >= 0 ? '+' : ''}${data.totalReturn.toFixed(2)}%`, 14, yPos);
  yPos += 12;

  // 2. PORTFOLIO HEALTH
  doc.setFontSize(14);
  doc.setTextColor(40);
  doc.text('Portfolio Health', 14, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.text(`Risk-Adjusted Return (Sharpe Ratio): ${data.sharpeRatio.toFixed(2)}`, 14, yPos);
  yPos += 6;
  doc.text(`Market Risk (Beta): ${data.beta.toFixed(2)}`, 14, yPos);
  yPos += 6;
  doc.text(`Maximum Drawdown: ${data.maxDrawdown.toFixed(2)}%`, 14, yPos);
  yPos += 6;
  doc.text(`Diversification Score: ${data.diversificationScore.toFixed(1)}/100`, 14, yPos);
  yPos += 10;

  // Risk Level Assessment
  const riskLevel = data.beta > 1.2 ? 'High' : data.beta > 0.8 ? 'Medium' : 'Low';
  const riskColor = data.beta > 1.2 ? [220, 38, 38] : data.beta > 0.8 ? [234, 179, 8] : [34, 197, 94];
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(`Overall Risk Level: ${riskLevel}`, 14, yPos);
  doc.setTextColor(60);
  yPos += 12;

  // 3. TOP HOLDINGS
  doc.setFontSize(14);
  doc.setTextColor(40);
  doc.text('Top Holdings', 14, yPos);
  yPos += 6;

  autoTable(doc, {
    startY: yPos,
    head: [['Symbol', 'Shares', 'Value', 'Allocation', 'Return']],
    body: data.holdings.slice(0, 10).map(h => [
      h.symbol,
      h.shares.toString(),
      `$${h.value.toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
      `${h.allocation.toFixed(1)}%`,
      `${h.return >= 0 ? '+' : ''}${h.return.toFixed(2)}%`
    ]),
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
    styles: { fontSize: 9 },
  });

  yPos = (doc as any).lastAutoTable.finalY + 10;

  // 4. RECOMMENDED CHANGES
  if (yPos > 220) {
    doc.addPage();
    yPos = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(40);
  doc.text('Recommended Changes', 14, yPos);
  yPos += 8;

  data.recommendations.forEach((rec, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text(`${index + 1}. ${rec.action}`, 14, yPos);
    yPos += 6;

    doc.setFontSize(9);
    doc.setTextColor(80);
    doc.text(`   Reason: ${rec.reason}`, 14, yPos);
    yPos += 5;
    doc.text(`   Expected Impact: ${rec.impact}`, 14, yPos);
    yPos += 8;
  });

  yPos += 4;

  // 5. RISKS & DISCLAIMERS
  if (yPos > 240) {
    doc.addPage();
    yPos = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(40);
  doc.text('Risks & Disclaimers', 14, yPos);
  yPos += 8;

  doc.setFontSize(8);
  doc.setTextColor(100);
  const disclaimer = [
    'This report is generated by SamrAI for informational purposes only and does not constitute financial advice.',
    'Past performance does not guarantee future results. All investments carry risk, including the potential loss of principal.',
    'The recommendations provided are based on quantitative analysis and AI-powered insights, but should not be',
    'considered as personalized investment advice. Please consult with a qualified financial advisor before making',
    'any investment decisions.',
    '',
    'Market conditions can change rapidly, and portfolio performance may vary significantly. Diversification does not',
    'guarantee profits or protect against losses. The risk metrics and projections are estimates based on historical',
    'data and may not accurately predict future performance.',
    '',
    'By using this report, you acknowledge that you understand these risks and limitations.'
  ];

  disclaimer.forEach(line => {
    if (yPos > 280) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, 14, yPos);
    yPos += 4;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Powered by SamrAI - AI-Powered Investment Platform', 105, 290, { align: 'center' });

  // Save the PDF
  doc.save(`SamrAI-Portfolio-Report-${new Date().toISOString().split('T')[0]}.pdf`);
}
